services:
  backend:
    profiles: ["backend-all", "all"]
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    profiles: ["all"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    profiles: ["backend-all", "all"]
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    profiles: ["backend-all", "all"]
    volumes:
      - ./backend/migrate:/migrations
    # Мы используем переменные, которые Docker Compose подтянет из .env
    command:
      - -path=/migrations/
      - -database
      - postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
      - up
    depends_on:
      postgres:
        condition: service_healthy # Ждем, пока база реально будет готова принимать запросы
    networks:
      - app_network
  # Сервис для ОТКАТА (на один шаг назад)
  migrate-down:
    image: migrate/migrate
    profiles: [ "tools" ] # Важно: этот сервис НЕ запустится при обычном docker-compose up
    volumes:
      - ./backend/migrate:/migrations
    command:
      - -path=/migrations/
      - -database
      - postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
      - down 1 # Откатывает ровно ОДНУ последнюю миграцию
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

  valkey:
    image: valkey/valkey:8-alpine
    profiles: ["backend-all", "all"]
    ports:
      - "${VALKEY_PORT}:6379"
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app_network
    restart: unless-stopped

volumes:
  postgres_data:
  valkey_data:

networks:
  app_network:
    driver: bridge
    name: my_diplom_network
