services:
  backend:
    image: ghcr.io/artemchadaev/diplom-backend:${APP_TAG:-latest}
    profiles: ["backend-all", "all"]
    env_file:
      - .env
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    image: ghcr.io/artemchadaev/diplom-frontend:${APP_TAG:-latest}
    profiles: ["all"] 
    env_file:
      - .env
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - PORT=3000
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    profiles: ["backend-all", "all"]
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    restart: unless-stopped

  migrate:
    image: ghcr.io/artemchadaev/diplom-migrate:${APP_TAG:-latest}
    profiles: ["backend-all", "all"]
    command:
      - -path=/migrations/
      - -database
      - postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
      - up
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

  migrate-down:
    image: ghcr.io/artemchadaev/diplom-migrate:${APP_TAG:-latest}
    profiles: [ "tools" ] 
    command:
      - -path=/migrations/
      - -database
      - postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
      - down 1
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

  valkey:
    image: valkey/valkey:8-alpine
    profiles: ["backend-all", "all"]
    ports:
      - "127.0.0.1:${VALKEY_PORT}:6379"
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app_network
    restart: unless-stopped

volumes:
  postgres_data:
  valkey_data:

networks:
  app_network:
    driver: bridge
    name: my_diplom_network